### ISSUE TITLE
Inefficient response_body collection

### ISSUE THREAD

**Issue by yashumitsu** [dmitry-j-mikhin/nginx-njs-log#1]
Hi, thank you for sharing this.

I had a problem with Nginx running out of memory when dealing with large response bodies (set up in front of Elasticsearch). A small change suggested by an Nginx developer helped me:

- https://github.com/nginx/njs/issues/412#issuecomment-1304375272

Hope you find it useful too.

**Comment by dmitry-j-mikhin** [comment]
Thanks @yashumitsu, will check later. Do you have any benchmarks or measurements of how much RAM usage has been reduced with the new method?

**Comment by dmitry-j-mikhin** [comment]
Added test to compare memory usage - https://github.com/dmitry-j-mikhin/nginx-njs-log/commit/35434c06a15cf807094b62c81337d798523fa50b
The old version with += does consume a lot of RAM, that's 6.5GB of RSS at the peak for a 5M response:
```
nginx: worker process pid 28
  VmPeak:	 6692708 kB
  VmSize:	   56268 kB
  VmHWM:	 6651696 kB
  VmRSS:	   15360 kB
```
New variant with array push - https://github.com/dmitry-j-mikhin/nginx-njs-log/commit/426c154e414ac6bc3bd2682a91f28fc70df16043 is much better, it consumes 75M RSS at the peak for a 5M response:
```
nginx: worker process pid 29
  VmPeak:	  118600 kB
  VmSize:	   52028 kB
  VmHWM:	   77592 kB
  VmRSS:	   11124 kB
```
