### ISSUE TITLE
Issue with binary data and new version of nginx

### ISSUE THREAD

**Issue by jweberst** [dmitry-j-mikhin/nginx-njs-log#3]
We noticed an issue in the newest version of nginx (it worked on older versions) where the body would get corrupted if binary data was in the response. This appears to be because js_body_filter is being called with the default which returns a string.

Here is the fix:

Modify the call of js_body_filter to be:

js_body_filter logging.response_filter buffer_type=buffer;

And modify the parsing of the body into an array to be:

response_body_arr.push(data.toString());

Hopefully this helps someone in the future!

**Comment by Nikoolayy1** [comment]
I agree that your solution is a way to go but it makes the logs unreadable . By adding proxy_set_header Accept-Encoding "";
you can also fix the bug as I think that as nginx examines the response body it messes the encoding as it probably decodes the body and then encode it again but does not indicate that in the response headers as there is no Content-Encoding header , so by just removing the request header for encoding you fix the issue.


Maybe also adding the correct encoding in a header with '' add_header Content-Encoding: xxx'' but I will not play more as the encoding breaks the logging to be seen in cleartext.

**Comment by jweberst** [comment]
Hello Nikoolayy1,

For our use case, we don't care if it is shows unreadable binary data. But it is a good point.

I think the logs would be unreadable regardless if binary data is being sent back to the client. Perhaps a better solution is to detect if its binary data being sent back and instead of showing it, say something like "Binary Data"

Maybe something like:

if(data.toString() !== data) {
  response_body_arr[0]("Binary Data Received ");
} else {
  response_body_arr.push(data.toString());
}


Thanks!
Justin

**Comment by Nikoolayy1** [comment]
I ended up using you solution as well as I needed only the response headers not the body, that I also don't need. Only for the response body my workaround proxy_set_header Accept-Encoding ""; could be used to log the body not in binary.

**Comment by dmitry-j-mikhin** [comment]
@jweberst @Nikoolayy1 thanks for info, I will check it with latest version of nginx.
